// generated help screen
import React, { useState } from 'react';
import { Linking, Pressable, ScrollView, StyleSheet, View } from 'react-native';
import { Text } from '@/theme';
const FAQS=[{q:'How do challenges work?',a:'Send a challenge to a friend, both players complete the same match, and scores sync live through Firestore. The winner is decided automatically once both players finish.'},{q:'Why can’t I receive push notifications?',a:'Expo Go has notification limitations on SDK 53+. Use a local development build for real notification testing.'},{q:'What happens if I play as a guest?',a:'Guest mode keeps progress locally on the device. Cloud syncing, social systems, and account recovery require a real account.'},{q:'How do I restore VIP purchases?',a:'Open the Store/Bazaar screen and use Restore Purchases. RevenueCat automatically re-checks your entitlement status.'},{q:'Why does my leaderboard rank change?',a:'Global rankings update from real player performance, XP growth, wins, streaks, and leaderboard refresh timing.'},{q:'Can I change my avatar and identity?',a:'Yes. Open Profile or Settings and use Edit Name & Avatar.'},{q:'Do challenge rewards sync online?',a:'Yes. XP, rewards, results, and completed challenge history sync per player account.'},{q:'What if my challenge gets stuck?',a:'Return to Friends and refresh the screen. Challenge completion syncs automatically after both players finish.'},{q:'Why are some features marked coming soon?',a:'The app is actively evolving with tournaments, seasonal systems, cosmetics, and expanded progression.'},{q:'Can I play offline?',a:'Some solo gameplay works locally, but social systems, cloud saves, rankings, and challenges require internet access.'}];
function FAQItem({q,a}:{q:string;a:string}){const[open,setOpen]=useState(false);return <View style={styles.faqCard}><Pressable onPress={()=>setOpen(v=>!v)}><Text style={styles.question}>{q}</Text></Pressable>{open&&<Text style={styles.answer}>{a}</Text>}</View>}
export default function HelpSupportScreen(){return <ScrollView style={styles.container} contentContainerStyle={styles.content}><Text style={styles.title}>Help & Support</Text><Text style={styles.sub}>Everything about gameplay, accounts, purchases, rankings, challenges, and support.</Text><View style={styles.heroCard}><Text style={styles.heroTitle}>Trivia Sweirki Support Center</Text><Text style={styles.heroText}>Version 1.0 • Social Challenges • RevenueCat Premium • Cloud Profiles</Text></View><View style={styles.section}><Text style={styles.sectionTitle}>Quick Support</Text><Pressable style={styles.actionBtn} onPress={()=>Linking.openURL('mailto:support@sweirki.com')}><Text style={styles.actionTitle}>Contact Support</Text><Text style={styles.actionSub}>Report bugs, purchase problems, challenge sync issues, or account problems.</Text></Pressable><Pressable style={styles.actionBtn} onPress={()=>Linking.openURL('mailto:feedback@sweirki.com')}><Text style={styles.actionTitle}>Send Feedback</Text><Text style={styles.actionSub}>Suggest new modes, tournaments, cosmetics, or progression systems.</Text></Pressable></View><View style={styles.section}><Text style={styles.sectionTitle}>Frequently Asked Questions</Text>{FAQS.map(item=><FAQItem key={item.q} q={item.q} a={item.a} />)}</View></ScrollView>}
const styles=StyleSheet.create({container:{flex:1,backgroundColor:'#0B1220'},content:{padding:20,paddingBottom:60},title:{color:'#F6C453',fontSize:28,fontWeight:'900'},sub:{marginTop:6,color:'#9AA3B2',lineHeight:20},heroCard:{marginTop:18,backgroundColor:'#141C2E',borderRadius:22,padding:18,borderWidth:1,borderColor:'#24304C'},heroTitle:{color:'#F6C453',fontSize:18,fontWeight:'800'},heroText:{marginTop:8,color:'#C6CEDB',lineHeight:20},section:{marginTop:22},sectionTitle:{marginBottom:12,color:'#F6C453',fontSize:16,fontWeight:'800'},actionBtn:{backgroundColor:'#141C2E',borderRadius:18,padding:16,borderWidth:1,borderColor:'#24304C',marginBottom:12},actionTitle:{color:'#FFFFFF',fontWeight:'800',fontSize:15},actionSub:{marginTop:6,color:'#9AA3B2',lineHeight:18},faqCard:{backgroundColor:'#141C2E',borderRadius:18,padding:16,borderWidth:1,borderColor:'#24304C',marginBottom:12},question:{color:'#FFFFFF',fontSize:14,fontWeight:'800'},answer:{marginTop:10,color:'#9AA3B2',lineHeight:20}})

