import { StyleSheet } from "react-native";
import { s } from "@/arena/theme/arenaSizing";

export const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: "#071226" },
  content: {
    alignItems: "center",
    paddingHorizontal: s(14),
    paddingTop: s(28),
    paddingBottom: s(40),
  },

  loadingContainer: {
    flex: 1,
    backgroundColor: "#071226",
    alignItems: "center",
    justifyContent: "center",
  },
  loadingText: { color: "#BBD7FF", fontSize: s(16), fontWeight: "800" },

  heroCard: {
    width: "100%",
    minHeight: s(256),
    borderRadius: s(28),
    padding: s(22),
    borderWidth: 1,
    borderColor: "rgba(190,231,255,0.30)",
    marginBottom: s(14),
    overflow: "hidden",
    backgroundColor: "#0A1830",
    shadowColor: "#000",
    shadowOpacity: 0.42,
    shadowRadius: s(28),
    shadowOffset: { width: 0, height: s(12) },
    elevation: 9,
  },
  heroImage: { borderRadius: s(28) },
  liveRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
  livePill: {
    color: "#120D05",
    backgroundColor: "#FFD36B",
    paddingHorizontal: s(10),
    paddingVertical: s(5),
    borderRadius: s(999),
    fontSize: s(11),
    fontWeight: "900",
    letterSpacing: 0.8,
    overflow: "hidden",
  },
  seasonPill: {
    color: "#D8E7FF",
    backgroundColor: "rgba(7,17,35,0.66)",
    borderWidth: 1,
    borderColor: "rgba(190,231,255,0.24)",
    paddingHorizontal: s(10),
    paddingVertical: s(5),
    borderRadius: s(999),
    fontSize: s(11),
    fontWeight: "900",
    overflow: "hidden",
  },
  heroCopy: {
    maxWidth: "72%",
    marginTop: s(30),
  },
  heroKicker: {
    color: "#FFD36B",
    fontSize: s(10),
    fontWeight: "900",
    letterSpacing: 1.15,
    textShadowColor: "rgba(0,0,0,0.9)",
    textShadowRadius: s(8),
  },
  heroTitle: {
    color: "#FFFFFF",
    fontSize: s(28),
    fontWeight: "900",
    marginTop: s(5),
    letterSpacing: -0.5,
    textShadowColor: "rgba(0,0,0,0.95)",
    textShadowRadius: s(10),
  },
  heroSubtitle: {
    color: "#D8E7FF",
    fontSize: s(13),
    fontWeight: "800",
    lineHeight: s(18),
    marginTop: s(7),
    textShadowColor: "rgba(0,0,0,0.9)",
    textShadowRadius: s(7),
  },
  heroStatsRow: {
    flexDirection: "row",
    gap: s(8),
    marginTop: "auto",
  },
  heroStatBox: {
    flex: 1,
    backgroundColor: "rgba(12,26,48,0.78)",
    borderWidth: 1,
    borderColor: "rgba(190,231,255,0.24)",
    borderRadius: s(16),
    paddingVertical: s(9),
    alignItems: "center",
  },
  heroStatBoxPrimary: {
    flex: 1.18,
    backgroundColor: "rgba(247,211,106,0.16)",
    borderWidth: 1,
    borderColor: "rgba(247,211,106,0.38)",
    borderRadius: s(16),
    paddingVertical: s(9),
    alignItems: "center",
  },
  heroStatValue: { color: "#FFD36B", fontSize: s(15), fontWeight: "900" },
  heroStatValueBlue: { color: "#8FE6FF", fontSize: s(15), fontWeight: "900" },
  heroStatLabel: {
    color: "#BBD7FF",
    fontSize: s(10),
    fontWeight: "900",
    marginTop: s(3),
    textTransform: "uppercase",
    letterSpacing: 0.55,
  },

  rankCard: {
    width: "100%",
    borderRadius: s(24),
    padding: s(15),
    borderWidth: 1,
    borderColor: "rgba(190,231,255,0.24)",
    marginBottom: s(12),
    overflow: "hidden",
  },
  rankTopRow: { flexDirection: "row", alignItems: "center", gap: s(13) },
  rankIcon: { width: s(62), height: s(62) },
  rankIconFallback: {
    width: s(62),
    height: s(62),
    borderRadius: s(22),
    backgroundColor: "rgba(247,211,106,0.12)",
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 1,
    borderColor: "rgba(247,211,106,0.45)",
  },
  rankIconFallbackText: { fontSize: s(30) },
  rankTextBlock: { flex: 1 },
  rankLabel: {
    color: "#FFD36B",
    fontSize: s(10),
    fontWeight: "900",
    letterSpacing: 0.9,
    textTransform: "uppercase",
  },
  rankName: {
    color: "#FFFFFF",
    fontSize: s(19),
    fontWeight: "900",
    marginTop: s(3),
  },
  rankSubtitle: {
    color: "#BBD7FF",
    fontSize: s(12),
    fontWeight: "800",
    marginTop: s(4),
    lineHeight: s(17),
  },
  progressBarWrapper: {
    height: s(10),
    borderRadius: s(999),
    overflow: "hidden",
    marginTop: s(15),
  },
  pressureRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    marginTop: s(9),
  },
  pressureText: { color: "#9DB6D8", fontSize: s(11), fontWeight: "900" },

  seasonLiveCard: {
    width: "100%",
    backgroundColor: "rgba(12,28,56,0.92)",
    borderRadius: s(19),
    padding: s(14),
    borderWidth: 1,
    borderColor: "rgba(143,230,255,0.30)",
    marginBottom: s(12),
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    gap: s(10),
  },
  seasonLiveCardExpired: {
    borderColor: "rgba(247,211,106,0.46)",
    backgroundColor: "rgba(30,25,42,0.94)",
  },
  seasonLiveLabel: {
    color: "#8FE6FF",
    fontSize: s(10),
    fontWeight: "900",
    letterSpacing: 1,
  },
  seasonLiveTitle: {
    color: "#FFFFFF",
    fontSize: s(15),
    fontWeight: "900",
    marginTop: s(4),
  },
  seasonLiveBody: {
    color: "#BBD7FF",
    fontSize: s(10),
    fontWeight: "800",
    lineHeight: s(14),
    marginTop: s(4),
  },
  seasonResetButton: {
    backgroundColor: "#8FEAFF",
    borderRadius: s(13),
    paddingHorizontal: s(12),
    paddingVertical: s(9),
    borderWidth: 1,
    borderColor: "#C6F1FF",
  },
  seasonResetButtonText: {
    color: "#062033",
    fontSize: s(11),
    fontWeight: "900",
  },
  seasonCountdown: {
    color: "#FFD36B",
    fontSize: s(27),
    fontWeight: "900",
  },

  majorCard: {
    width: "100%",
    borderRadius: s(22),
    padding: s(15),
    borderWidth: 1,
    borderColor: "rgba(247,211,106,0.35)",
    marginBottom: s(12),
    overflow: "hidden",
  },
  cardHeaderRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
  majorLabel: {
    color: "#FFD36B",
    fontSize: s(10),
    fontWeight: "900",
    letterSpacing: 1,
  },
  countdownText: { color: "#8FE6FF", fontSize: s(11), fontWeight: "900" },
  majorTitle: {
    color: "#FFFFFF",
    fontSize: s(19),
    fontWeight: "900",
    marginTop: s(9),
  },
  majorBody: {
    color: "#D8E7FF",
    fontSize: s(12),
    fontWeight: "800",
    lineHeight: s(18),
    marginTop: s(5),
  },
  primaryButton: {
    backgroundColor: "#10233D",
    borderRadius: s(16),
    paddingVertical: s(13),
    alignItems: "center",
    marginTop: s(13),
    borderWidth: 1,
    borderColor: "#D6A84F",
    shadowColor: "#4DA3FF",
    shadowOpacity: 0.28,
    shadowRadius: s(10),
    shadowOffset: { width: 0, height: 0 },
    elevation: 5,
  },
  primaryButtonDisabled: { opacity: 0.55 },
  primaryButtonText: { color: "#F7D37A", fontWeight: "900", fontSize: s(14) },

  energyGrid: {
    width: "100%",
    flexDirection: "row",
    gap: s(10),
    marginBottom: s(12),
  },
  energyCard: {
    flex: 1,
    backgroundColor: "rgba(12,28,56,0.92)",
    borderRadius: s(18),
    padding: s(13),
    borderWidth: 1,
    borderColor: "rgba(190,231,255,0.20)",
  },
  glowBlue: { borderColor: "#4FC3F7" },
  glowOrange: { borderColor: "#FF7043" },
  energyTitle: { color: "#BBD7FF", fontSize: s(11), fontWeight: "900" },
  energyValue: {
    color: "#FFFFFF",
    fontSize: s(22),
    fontWeight: "900",
    marginTop: s(6),
  },
  energyHint: {
    color: "#9DB6D8",
    fontSize: s(10),
    fontWeight: "800",
    lineHeight: s(14),
    marginTop: s(7),
  },
  smallBar: {
    height: s(7),
    borderRadius: s(999),
    overflow: "hidden",
    marginTop: s(9),
  },

  prestigeRow: {
    width: "100%",
    flexDirection: "row",
    gap: s(10),
    marginBottom: s(12),
  },
  prestigeCard: {
    flex: 1,
    backgroundColor: "rgba(8,19,40,0.96)",
    borderRadius: s(18),
    padding: s(13),
    borderWidth: 1,
    borderColor: "rgba(190,231,255,0.20)",
  },
  prestigeLabel: {
    color: "#FFD36B",
    fontSize: s(10),
    fontWeight: "900",
    letterSpacing: 0.8,
  },
  prestigeLabelBlue: {
    color: "#8FE6FF",
    fontSize: s(10),
    fontWeight: "900",
    letterSpacing: 0.8,
  },
  prestigeTitle: {
    color: "#FFFFFF",
    fontSize: s(16),
    fontWeight: "900",
    marginTop: s(5),
  },
  prestigeText: {
    color: "#9DB6D8",
    fontSize: s(10),
    fontWeight: "800",
    lineHeight: s(14),
    marginTop: s(5),
  },

  lastSeasonCard: {
    width: "100%",
    backgroundColor: "rgba(20,38,72,0.94)",
    borderRadius: s(18),
    padding: s(13),
    borderWidth: 1,
    borderColor: "rgba(247,211,106,0.26)",
    marginBottom: s(12),
  },
  lastSeasonLabel: {
    color: "#FFD36B",
    fontSize: s(10),
    fontWeight: "900",
    letterSpacing: 0.9,
  },
  lastSeasonTitle: {
    color: "#FFFFFF",
    fontSize: s(15),
    fontWeight: "900",
    marginTop: s(5),
  },
  lastSeasonText: {
    color: "#BBD7FF",
    fontSize: s(11),
    fontWeight: "800",
    lineHeight: s(16),
    marginTop: s(5),
  },
  lastSeasonActions: {
    flexDirection: "row",
    alignItems: "center",
    gap: s(8),
    marginTop: s(12),
  },
  lastSeasonClaimButton: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#8FEAFF",
    borderRadius: s(13),
    paddingVertical: s(10),
    borderWidth: 1,
    borderColor: "#C6F1FF",
  },
  lastSeasonClaimButtonDisabled: {
    backgroundColor: "rgba(75,85,105,0.72)",
    borderColor: "rgba(190,210,230,0.18)",
  },
  lastSeasonClaimButtonText: {
    color: "#062033",
    fontSize: s(11),
    fontWeight: "900",
  },
  lastSeasonDismissButton: {
    paddingHorizontal: s(12),
    paddingVertical: s(10),
    borderRadius: s(13),
    borderWidth: 1,
    borderColor: "rgba(143,230,255,0.24)",
    backgroundColor: "rgba(8,22,44,0.78)",
  },
  lastSeasonDismissText: {
    color: "#BBD7FF",
    fontSize: s(11),
    fontWeight: "900",
  },

  eventCard: {
    width: "100%",
    backgroundColor: "#0E1930",
    borderRadius: s(18),
    padding: s(14),
    borderWidth: 1,
    borderColor: "#355D9B",
    marginBottom: s(14),
    shadowColor: "#4DA3FF",
    shadowOpacity: 0.18,
    shadowRadius: s(12),
    shadowOffset: { width: 0, height: 0 },
    elevation: 4,
  },
  eventLabel: {
    color: "#F7D37A",
    fontSize: s(10),
    fontWeight: "900",
    letterSpacing: 1,
  },
  eventTitle: {
    color: "#FFFFFF",
    fontSize: s(18),
    fontWeight: "900",
    marginTop: s(7),
  },
  eventBody: {
    color: "#BFE8FF",
    fontSize: s(12),
    fontWeight: "800",
    lineHeight: s(17),
    marginTop: s(6),
  },
  eventReward: {
    color: "#8FEAFF",
    fontSize: 11,
    lineHeight: 15,
    fontWeight: "900",
    marginTop: 6,
  },

  modesWrapper: { width: "100%" },
  sectionTitle: {
    color: "#FFFFFF",
    fontSize: s(18),
    fontWeight: "900",
    marginBottom: s(10),
    letterSpacing: -0.2,
  },

  cosmeticStrip: {
    marginTop: s(12),
    padding: s(10),
    borderRadius: s(16),
    borderWidth: 1,
    borderColor: "rgba(255, 211, 77, 0.30)",
    backgroundColor: "rgba(7,17,35,0.62)",
    flexDirection: "row",
    alignItems: "center",
    gap: s(10),
  },
  cosmeticBannerThumb: {
    width: s(64),
    height: s(36),
    borderRadius: s(10),
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.18)",
  },
  cosmeticStripText: { flex: 1 },
  cosmeticStripTitle: {
    color: "#FFD36B",
    fontSize: s(11),
    fontWeight: "900",
    letterSpacing: 0.4,
  },
  cosmeticStripBody: {
    color: "#EDEBFF",
    fontSize: s(11),
    fontWeight: "700",
    marginTop: s(3),
  },
});




