import { StyleSheet } from "react-native";

const GOLD = "#FFD66E";
const CYAN = "#9FE7FF";
const BLUE = "#58B8FF";
const INK = "#07111F";

export const styles = StyleSheet.create({
  shellContent: {
    flex: 1,
    paddingTop: 0,
    paddingBottom: 0,
  },
  backgroundArt: {
    ...StyleSheet.absoluteFillObject,
    width: "100%",
    height: "100%",
    opacity: 0.72,
  },
  content: {
    paddingHorizontal: 20,
    paddingTop: 18,
    paddingBottom: 52,
  },
  header: {
    flexDirection: "row",
    alignItems: "flex-start",
    justifyContent: "space-between",
    marginBottom: 14,
    gap: 12,
  },
  headerCopy: {
    flex: 1,
  },
  kicker: {
    color: "#7E8EA7",
    letterSpacing: 1.6,
    marginBottom: 3,
    opacity: 0.86,
  },
  screenTitle: {
    color: "#F4FAFF",
    letterSpacing: -0.4,
  },
  screenSub: {
    color: CYAN,
    marginTop: 2,
    fontWeight: "800",
  },
  liveBadge: {
    flexDirection: "row",
    alignItems: "center",
    borderWidth: 1,
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: 999,
    marginTop: 6,
  },
  vipLiveBadge: {
    backgroundColor: "rgba(255,214,110,0.13)",
    borderColor: "rgba(255,214,110,0.38)",
  },
  standardLiveBadge: {
    backgroundColor: "rgba(159,231,255,0.12)",
    borderColor: "rgba(159,231,255,0.34)",
  },
  liveDot: {
    width: 7,
    height: 7,
    borderRadius: 4,
    marginRight: 6,
  },
  heroCard: {
    minHeight: 228,
    marginBottom: 12,
    borderRadius: 26,
    overflow: "hidden",
    backgroundColor: INK,
    borderWidth: 1,
    borderColor: "rgba(255,214,110,0.42)",
    shadowColor: "#1E8CFF",
    shadowOpacity: 0.22,
    shadowRadius: 20,
    shadowOffset: { width: 0, height: 10 },
    elevation: 9,
  },
  heroArt: {
    ...StyleSheet.absoluteFillObject,
    width: "100%",
    height: "100%",
    opacity: 0.98,
  },
  heroInner: {
    flex: 1,
    padding: 16,
    justifyContent: "space-between",
  },
  profileHeader: {
    flexDirection: "row",
    alignItems: "center",
    gap: 14,
  },
  avatarOuterGlow: {
    width: 104,
    height: 104,
    borderRadius: 52,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "rgba(255,214,110,0.12)",
    borderWidth: 1,
    borderColor: "rgba(255,214,110,0.46)",
    shadowColor: GOLD,
    shadowOpacity: 0.35,
    shadowRadius: 14,
    shadowOffset: { width: 0, height: 0 },
  },
  avatarFrame: {
    width: 92,
    height: 92,
    borderRadius: 46,
    borderWidth: 2,
    borderColor: GOLD,
    alignItems: "center",
    justifyContent: "center",
    overflow: "hidden",
    backgroundColor: "rgba(7,17,31,0.88)",
  },
  avatar: {
    width: "100%",
    height: "100%",
    borderRadius: 46,
  },
  avatarFallback: {
    width: "100%",
    height: "100%",
    borderRadius: 46,
    backgroundColor: "#13213A",
  },
  profileHeaderText: {
    flex: 1,
    minWidth: 0,
  },
  playerName: {
    color: GOLD,
    fontSize: 25,
    fontWeight: "900",
    letterSpacing: -0.45,
    textShadowColor: "rgba(0,0,0,0.95)",
    textShadowRadius: 9,
  },
  playerSub: {
    color: CYAN,
    fontSize: 12,
    fontWeight: "800",
    marginTop: 3,
    textShadowColor: "rgba(0,0,0,0.88)",
    textShadowRadius: 7,
  },
  identityBadgeRow: {
    flexDirection: "row",
    gap: 7,
    flexWrap: "wrap",
    marginTop: 10,
  },
  identityBadge: {
    paddingHorizontal: 10,
    paddingVertical: 5,
    borderRadius: 999,
    backgroundColor: "rgba(7,17,31,0.62)",
    borderWidth: 1,
    borderColor: "rgba(159,231,255,0.28)",
  },
  identityBadgeText: {
    color: "#D8E7FF",
    fontSize: 10,
    fontWeight: "900",
  },
  xpMetaRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 8,
  },
  xpLabel: {
    color: CYAN,
    fontSize: 11,
    fontWeight: "900",
    textShadowColor: "rgba(0,0,0,0.88)",
    textShadowRadius: 7,
  },
  xpText: {
    color: "#D8E7FF",
    fontSize: 11,
    fontWeight: "900",
    textShadowColor: "rgba(0,0,0,0.95)",
    textShadowRadius: 8,
  },
  xpBar: {
    height: 10,
    borderRadius: 999,
    overflow: "hidden",
    backgroundColor: "rgba(216,231,255,0.18)",
    borderWidth: 1,
    borderColor: "rgba(159,231,255,0.16)",
  },
  xpFill: {
    height: "100%",
    backgroundColor: CYAN,
    shadowColor: BLUE,
    shadowOpacity: 0.75,
    shadowRadius: 8,
  },
  statsRow: {
    flexDirection: "row",
    gap: 8,
    marginBottom: 12,
  },
  miniStat: {
    flex: 1,
    minHeight: 72,
    borderRadius: 18,
    overflow: "hidden",
    backgroundColor: "rgba(7,17,31,0.9)",
    borderWidth: 1,
    borderColor: "rgba(110,170,255,0.26)",
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: 5,
  },
  miniStatGlow: {
    position: "absolute",
    top: 0,
    left: 10,
    right: 10,
    height: 1,
    opacity: 0.7,
  },
  miniStatValue: {
    fontSize: 16,
    fontWeight: "900",
    marginBottom: 2,
  },
  miniStatLabel: {
    color: "#9FB3CE",
    fontSize: 9.5,
    fontWeight: "800",
    textAlign: "center",
  },
  vipPanel: {
    minHeight: 86,
    marginBottom: 12,
    borderRadius: 22,
    overflow: "hidden",
    backgroundColor: INK,
    borderWidth: 1,
    borderColor: "rgba(255,214,110,0.36)",
  },
  vipPanelArt: {
    ...StyleSheet.absoluteFillObject,
    width: "100%",
    height: "100%",
    opacity: 0.94,
  },
  vipCopy: {
    flex: 1,
    flexDirection: "row",
    alignItems: "center",
    padding: 13,
    gap: 11,
  },
  vipIcon: {
    width: 42,
    height: 42,
  },
  vipTextWrap: {
    flex: 1,
    minWidth: 0,
  },
  vipTitle: {
    color: GOLD,
    fontSize: 13,
    fontWeight: "900",
    letterSpacing: 0.3,
    textShadowColor: "rgba(0,0,0,0.92)",
    textShadowRadius: 8,
  },
  vipSub: {
    color: "#D8E7FF",
    fontSize: 10.5,
    fontWeight: "800",
    marginTop: 3,
  },
  vipButton: {
    paddingHorizontal: 12,
    paddingVertical: 7,
    borderRadius: 999,
    backgroundColor: "rgba(255,214,110,0.18)",
    borderWidth: 1,
    borderColor: "rgba(255,214,110,0.42)",
  },
  vipButtonText: {
    color: GOLD,
    fontSize: 11,
    fontWeight: "900",
  },
  accountPanel: {
    marginBottom: 14,
    padding: 13,
    borderRadius: 18,
    backgroundColor: "rgba(7,17,31,0.74)",
    borderWidth: 1,
    borderColor: "rgba(159,231,255,0.18)",
    alignItems: "center",
  },
  accountText: {
    color: "#D8E7FF",
    fontSize: 11,
    fontWeight: "800",
    textAlign: "center",
  },
  accountSub: {
    color: "#9FB3CE",
    fontSize: 10,
    marginTop: 3,
    textAlign: "center",
  },
  accountButtonRow: {
    flexDirection: "row",
    gap: 8,
    marginTop: 8,
  },
  accountButton: {
    marginTop: 8,
    paddingHorizontal: 14,
    paddingVertical: 7,
    borderRadius: 999,
    backgroundColor: "rgba(159,231,255,0.1)",
    borderWidth: 1,
    borderColor: "rgba(159,231,255,0.28)",
  },
  accountButtonText: {
    color: CYAN,
    fontSize: 11,
    fontWeight: "900",
  },
  identityGrid: {
    flexDirection: "row",
    gap: 9,
    marginBottom: 16,
  },
  identityCard: {
    flex: 1,
    minHeight: 112,
    borderRadius: 20,
    backgroundColor: "rgba(7,17,31,0.88)",
    borderWidth: 1,
    borderColor: "rgba(110,170,255,0.26)",
    alignItems: "center",
    justifyContent: "center",
    padding: 9,
    overflow: "hidden",
  },
  identityIcon: {
    width: 35,
    height: 35,
    marginBottom: 5,
  },
  identityCrown: {
    fontSize: 28,
    marginBottom: 5,
  },
  identityValue: {
    color: GOLD,
    fontSize: 18,
    fontWeight: "900",
  },
  identityLabel: {
    color: "#9FB3CE",
    fontSize: 9.5,
    fontWeight: "800",
    marginTop: 3,
    textAlign: "center",
  },
  grid: {
    flexDirection: "row",
    flexWrap: "wrap",
    justifyContent: "space-between",
    marginBottom: 8,
  },
  artTile: {
    width: "48.5%",
    minHeight: 118,
    marginBottom: 10,
    borderRadius: 22,
    overflow: "hidden",
    backgroundColor: INK,
    borderWidth: 1,
    borderColor: "rgba(110,170,255,0.28)",
    shadowColor: "#1E8CFF",
    shadowOpacity: 0.15,
    shadowRadius: 12,
    shadowOffset: { width: 0, height: 7 },
    elevation: 6,
  },
  artImage: {
    ...StyleSheet.absoluteFillObject,
    width: "100%",
    height: "100%",
    opacity: 0.98,
  },
  artAccent: {
    position: "absolute",
    left: 12,
    right: 12,
    top: 0,
    height: 1,
    opacity: 0.76,
  },
  artBorderGlow: {
    ...StyleSheet.absoluteFillObject,
    borderRadius: 22,
    borderWidth: 1,
  },
  artCopy: {
    flex: 1,
    justifyContent: "flex-end",
    padding: 12,
    paddingRight: 8,
    zIndex: 5,
  },
  artTitle: {
    fontSize: 16,
    fontWeight: "900",
    letterSpacing: -0.22,
    marginBottom: 1,
    textShadowColor: "rgba(0,0,0,0.96)",
    textShadowRadius: 9,
  },
  artSub: {
    color: "#D8E7FF",
    fontSize: 10.5,
    fontWeight: "800",
    lineHeight: 13,
    textShadowColor: "rgba(0,0,0,0.94)",
    textShadowRadius: 7,
  },
  prestigePanel: {
    minHeight: 136,
    marginBottom: 14,
    borderRadius: 23,
    overflow: "hidden",
    backgroundColor: INK,
    borderWidth: 1,
    borderColor: "rgba(110,170,255,0.24)",
  },
  panelArt: {
    ...StyleSheet.absoluteFillObject,
    width: "100%",
    height: "100%",
    opacity: 0.96,
  },
  panelRim: {
    ...StyleSheet.absoluteFillObject,
    borderRadius: 23,
    borderWidth: 1,
  },
  panelCopy: {
    padding: 14,
    paddingRight: 90,
  },
  panelLabel: {
    fontSize: 10,
    fontWeight: "900",
    letterSpacing: 1.2,
    textShadowColor: "rgba(0,0,0,0.9)",
    textShadowRadius: 7,
  },
  panelTitle: {
    color: "#FFFFFF",
    fontSize: 17,
    fontWeight: "900",
    marginTop: 8,
    textShadowColor: "rgba(0,0,0,0.92)",
    textShadowRadius: 8,
  },
  panelBody: {
    color: "#D8E7FF",
    fontSize: 11,
    fontWeight: "700",
    lineHeight: 17,
    marginTop: 7,
    textShadowColor: "rgba(0,0,0,0.86)",
    textShadowRadius: 6,
  },
  sectionCard: {
    marginBottom: 14,
    padding: 14,
    borderRadius: 22,
    backgroundColor: "rgba(7,17,31,0.82)",
    borderWidth: 1,
    borderColor: "rgba(110,170,255,0.22)",
  },
  pills: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 8,
  },
  pill: {
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 999,
    backgroundColor: "rgba(255,214,110,0.12)",
    borderWidth: 1,
    borderColor: "rgba(255,214,110,0.32)",
  },
  pillText: {
    color: GOLD,
    fontSize: 12,
    fontWeight: "900",
  },
  historyRow: {
    paddingVertical: 11,
    borderBottomWidth: 1,
    borderBottomColor: "rgba(159,231,255,0.14)",
  },
  historyText: {
    color: "#FFFFFF",
    fontSize: 12,
    fontWeight: "900",
  },
  historyDate: {
    color: "#9FB3CE",
    marginTop: 2,
    fontSize: 11,
    fontWeight: "700",
  },
  empty: {
    color: "#9FB3CE",
    fontSize: 11,
    lineHeight: 17,
    fontWeight: "700",
  },
  pressed: {
    opacity: 0.86,
    transform: [{ scale: 0.985 }],
  },
});





