// src/cosmetics/catalog.ts
/**
 * ============================================================
 * COSMETICS CATALOG — PHASE 5.2 STORE CONTENT EXPANSION
 * ============================================================
 * Data-only catalog. Cosmetics never affect gameplay.
 */

import { CosmeticItem, CosmeticCategory, CosmeticRarity } from "./types";

export const COSMETIC_RARITY_PRICE_BANDS = {
  COMMON: {
    COINS: { min: 50, max: 150 },
  },
  RARE: {
    COINS: { min: 200, max: 500 },
  },
  EPIC: {
    COINS: { min: 600, max: 1200 },
    GEMS: { min: 5, max: 15 },
  },
  LEGENDARY: {
    GEMS: { min: 20, max: 50 },
  },
} as const;

export const COSMETICS_CATALOG: CosmeticItem[] = [
  {
    id: "avatar_default_blue",
    category: CosmeticCategory.AVATAR,
    rarity: CosmeticRarity.COMMON,
    name: "Blue Starter Avatar",
    description: "A clean blue avatar for new heroes.",
    icon: "avatar_blue_01",
    price: { currency: "COINS", amount: 100 },
  },
  {
    id: "avatar_sunrise_orange",
    category: CosmeticCategory.AVATAR,
    rarity: CosmeticRarity.COMMON,
    name: "Sunrise Avatar",
    description: "Warm orange style for daily players.",
    icon: "avatar_sunrise_01",
    price: { currency: "COINS", amount: 120 },
  },
  {
    id: "avatar_mint_focus",
    category: CosmeticCategory.AVATAR,
    rarity: CosmeticRarity.COMMON,
    name: "Mint Focus Avatar",
    description: "A calm avatar for clean streak runs.",
    icon: "avatar_mint_01",
    price: { currency: "COINS", amount: 140 },
  },
  {
    id: "avatar_neon_brain",
    category: CosmeticCategory.AVATAR,
    rarity: CosmeticRarity.RARE,
    name: "Neon Brain Avatar",
    description: "Bright trivia energy for fast answers.",
    icon: "avatar_neon_brain_01",
    price: { currency: "COINS", amount: 450 },
  },
  {
    id: "avatar_galaxy_ace",
    category: CosmeticCategory.AVATAR,
    rarity: CosmeticRarity.EPIC,
    name: "Galaxy Ace Avatar",
    description: "A premium cosmic avatar for top runs.",
    icon: "avatar_galaxy_ace_01",
    price: { currency: "GEMS", amount: 12 },
  },

  {
    id: "avatar_frame_gold",
    category: CosmeticCategory.AVATAR_FRAME,
    rarity: CosmeticRarity.RARE,
    name: "Gold Frame",
    description: "A shiny gold avatar frame.",
    icon: "frame_gold_01",
    price: { currency: "COINS", amount: 400 },
  },
  {
    id: "frame_silver_clean",
    category: CosmeticCategory.AVATAR_FRAME,
    rarity: CosmeticRarity.COMMON,
    name: "Silver Clean Frame",
    description: "A simple polished frame.",
    icon: "frame_silver_clean_01",
    price: { currency: "COINS", amount: 90 },
  },
  {
    id: "frame_emerald_streak",
    category: CosmeticCategory.AVATAR_FRAME,
    rarity: CosmeticRarity.RARE,
    name: "Emerald Streak Frame",
    description: "A green frame for streak hunters.",
    icon: "frame_emerald_streak_01",
    price: { currency: "COINS", amount: 500 },
  },
  {
    id: "frame_cosmic_pulse",
    category: CosmeticCategory.AVATAR_FRAME,
    rarity: CosmeticRarity.EPIC,
    name: "Cosmic Pulse Frame",
    description: "Animated-feel cosmic profile energy.",
    icon: "frame_cosmic_pulse_01",
    price: { currency: "GEMS", amount: 15 },
  },
  {
    id: "frame_royal_legend",
    category: CosmeticCategory.AVATAR_FRAME,
    rarity: CosmeticRarity.LEGENDARY,
    name: "Royal Legend Frame",
    description: "A legendary frame for elite collectors.",
    icon: "frame_royal_legend_01",
    price: { currency: "GEMS", amount: 35 },
    limited: true,
  },

  {
    id: "profile_bg_night",
    category: CosmeticCategory.PROFILE_BACKGROUND,
    rarity: CosmeticRarity.EPIC,
    name: "Night Sky Background",
    description: "A calm night sky for your profile.",
    icon: "bg_night_01",
    price: { currency: "GEMS", amount: 10 },
  },
  {
    id: "bg_arcade_grid",
    category: CosmeticCategory.PROFILE_BACKGROUND,
    rarity: CosmeticRarity.RARE,
    name: "Arcade Grid Background",
    description: "Retro arcade style for quiz nights.",
    icon: "bg_arcade_grid_01",
    price: { currency: "COINS", amount: 450 },
  },
  {
    id: "bg_library_glow",
    category: CosmeticCategory.PROFILE_BACKGROUND,
    rarity: CosmeticRarity.EPIC,
    name: "Library Glow Background",
    description: "A premium knowledge-room profile look.",
    icon: "bg_library_glow_01",
    price: { currency: "COINS", amount: 1000 },
  },
  {
    id: "bg_stadium_lights",
    category: CosmeticCategory.PROFILE_BACKGROUND,
    rarity: CosmeticRarity.EPIC,
    name: "Stadium Lights Background",
    description: "Big-event energy for competitive players.",
    icon: "bg_stadium_lights_01",
    price: { currency: "GEMS", amount: 14 },
  },
  {
    id: "bg_legend_nebula",
    category: CosmeticCategory.PROFILE_BACKGROUND,
    rarity: CosmeticRarity.LEGENDARY,
    name: "Legend Nebula Background",
    description: "A limited legendary profile background.",
    icon: "bg_legend_nebula_01",
    price: { currency: "GEMS", amount: 45 },
    limited: true,
  },

  {
    id: "badge_starter",
    category: CosmeticCategory.BADGE,
    rarity: CosmeticRarity.COMMON,
    name: "Starter Badge",
    description: "Awarded to every new hero.",
    icon: "badge_starter_01",
    price: { currency: "COINS", amount: 50 },
  },
  {
    id: "badge_daily_grinder",
    category: CosmeticCategory.BADGE,
    rarity: CosmeticRarity.COMMON,
    name: "Daily Grinder Badge",
    description: "For players who show up every day.",
    icon: "badge_daily_grinder_01",
    price: { currency: "COINS", amount: 150 },
  },
  {
    id: "badge_speed_round",
    category: CosmeticCategory.BADGE,
    rarity: CosmeticRarity.RARE,
    name: "Speed Round Badge",
    description: "For fast-answer trivia energy.",
    icon: "badge_speed_round_01",
    price: { currency: "COINS", amount: 350 },
  },
  {
    id: "badge_brainiac",
    category: CosmeticCategory.BADGE,
    rarity: CosmeticRarity.EPIC,
    name: "Brainiac Badge",
    description: "A premium badge for knowledge flexing.",
    icon: "badge_brainiac_01",
    price: { currency: "GEMS", amount: 8 },
  },
  {
    id: "badge_legend_founder",
    category: CosmeticCategory.BADGE,
    rarity: CosmeticRarity.LEGENDARY,
    name: "Legend Founder Badge",
    description: "Awarded to early legends.",
    icon: "badge_founder_legend",
    price: { currency: "GEMS", amount: 30 },
    limited: true,
  },
  {
    id: "arena_banner_neon_champion",
    category: CosmeticCategory.ARENA_BANNER,
    rarity: CosmeticRarity.EPIC,
    name: "Neon Champion Banner",
    description: "A premium arena banner for ranked competitors.",
    icon: "arena_banner_neon_champion_01",
    price: { currency: "GEMS", amount: 12 },
    unlockType: "STORE",
  },
  {
    id: "arena_banner_royal_vip",
    category: CosmeticCategory.ARENA_BANNER,
    rarity: CosmeticRarity.LEGENDARY,
    name: "Royal VIP Banner",
    description: "A VIP-only banner for elite profiles and arena lobbies.",
    icon: "arena_banner_royal_vip_01",
    price: { currency: "GEMS", amount: 30 },
    vipOnly: true,
    unlockType: "VIP",
  },
  {
    id: "trail_gold_spark",
    category: CosmeticCategory.ANSWER_TRAIL,
    rarity: CosmeticRarity.EPIC,
    name: "Gold Spark Trail",
    description: "A premium answer trail for high-energy matches.",
    icon: "answer_trail_gold_spark_01",
    price: { currency: "GEMS", amount: 10 },
    unlockType: "STORE",
  },
  {
    id: "trail_cosmic_vip",
    category: CosmeticCategory.ANSWER_TRAIL,
    rarity: CosmeticRarity.LEGENDARY,
    name: "Cosmic VIP Trail",
    description: "VIP-only cosmic answer feedback.",
    icon: "answer_trail_cosmic_vip_01",
    price: { currency: "GEMS", amount: 25 },
    vipOnly: true,
    unlockType: "VIP",
  },
  {
    id: "streak_aura_fire_7",
    category: CosmeticCategory.STREAK_AURA,
    rarity: CosmeticRarity.EPIC,
    name: "7-Day Fire Aura",
    description: "A streak aura for committed daily players.",
    icon: "streak_aura_fire_7_01",
    price: { currency: "GEMS", amount: 15 },
    unlockType: "STORE",
  },
  {
    id: "streak_aura_diamond_vip",
    category: CosmeticCategory.STREAK_AURA,
    rarity: CosmeticRarity.LEGENDARY,
    name: "Diamond VIP Streak Aura",
    description: "A VIP-only streak aura for elite retention flex.",
    icon: "streak_aura_diamond_vip_01",
    price: { currency: "GEMS", amount: 35 },
    vipOnly: true,
    unlockType: "VIP",
  },


  {
    id: "avatar_quiz_master",
    category: CosmeticCategory.AVATAR,
    rarity: CosmeticRarity.RARE,
    name: "Quiz Master Avatar",
    description: "A polished avatar for serious trivia players.",
    icon: "avatar_quiz_master_01",
    price: { currency: "COINS", amount: 500 },
  },
  {
    id: "avatar_mystic_owl",
    category: CosmeticCategory.AVATAR,
    rarity: CosmeticRarity.EPIC,
    name: "Mystic Owl Avatar",
    description: "A wise premium avatar with moonlit trivia energy.",
    icon: "avatar_mystic_owl_01",
    price: { currency: "GEMS", amount: 10 },
  },
  {
    id: "avatar_robot_genius",
    category: CosmeticCategory.AVATAR,
    rarity: CosmeticRarity.EPIC,
    name: "Robot Genius Avatar",
    description: "A futuristic avatar built for perfect answers.",
    icon: "avatar_robot_genius_01",
    price: { currency: "GEMS", amount: 12 },
  },
  {
    id: "avatar_vip_crown",
    category: CosmeticCategory.AVATAR,
    rarity: CosmeticRarity.LEGENDARY,
    name: "VIP Crown Avatar",
    description: "A royal VIP avatar for premium members.",
    icon: "avatar_vip_crown_01",
    price: { currency: "GEMS", amount: 35 },
    vipOnly: true,
    unlockType: "VIP",
    limited: true,
  },
  {
    id: "frame_neon_blue",
    category: CosmeticCategory.AVATAR_FRAME,
    rarity: CosmeticRarity.RARE,
    name: "Neon Blue Frame",
    description: "A clean neon frame for modern profiles.",
    icon: "frame_neon_blue_01",
    price: { currency: "COINS", amount: 450 },
  },
  {
    id: "frame_fire_streak",
    category: CosmeticCategory.AVATAR_FRAME,
    rarity: CosmeticRarity.EPIC,
    name: "Fire Streak Frame",
    description: "A heated frame for high-streak players.",
    icon: "frame_fire_streak_01",
    price: { currency: "GEMS", amount: 12 },
  },
  {
    id: "frame_diamond_vip",
    category: CosmeticCategory.AVATAR_FRAME,
    rarity: CosmeticRarity.LEGENDARY,
    name: "Diamond VIP Frame",
    description: "A premium diamond frame for VIP identity.",
    icon: "frame_diamond_vip_01",
    price: { currency: "GEMS", amount: 40 },
    vipOnly: true,
    unlockType: "VIP",
    limited: true,
  },
  {
    id: "bg_trophy_hall",
    category: CosmeticCategory.PROFILE_BACKGROUND,
    rarity: CosmeticRarity.RARE,
    name: "Trophy Hall Background",
    description: "A prestigious profile background for winners.",
    icon: "bg_trophy_hall_01",
    price: { currency: "COINS", amount: 500 },
  },
  {
    id: "bg_cyber_stage",
    category: CosmeticCategory.PROFILE_BACKGROUND,
    rarity: CosmeticRarity.EPIC,
    name: "Cyber Stage Background",
    description: "A glowing stage background for competitive players.",
    icon: "bg_cyber_stage_01",
    price: { currency: "GEMS", amount: 12 },
  },
  {
    id: "bg_vip_lounge",
    category: CosmeticCategory.PROFILE_BACKGROUND,
    rarity: CosmeticRarity.LEGENDARY,
    name: "VIP Lounge Background",
    description: "A luxury VIP profile background.",
    icon: "bg_vip_lounge_01",
    price: { currency: "GEMS", amount: 45 },
    vipOnly: true,
    unlockType: "VIP",
    limited: true,
  },
  {
    id: "badge_arena_champion",
    category: CosmeticCategory.BADGE,
    rarity: CosmeticRarity.EPIC,
    name: "Arena Champion Badge",
    description: "A badge for players who dominate the arena.",
    icon: "badge_arena_champion_01",
    price: { currency: "GEMS", amount: 10 },
  },
  {
    id: "badge_perfect_score",
    category: CosmeticCategory.BADGE,
    rarity: CosmeticRarity.RARE,
    name: "Perfect Score Badge",
    description: "A clean badge for perfect rounds.",
    icon: "badge_perfect_score_01",
    price: { currency: "COINS", amount: 450 },
  },
  {
    id: "badge_vip_crown",
    category: CosmeticCategory.BADGE,
    rarity: CosmeticRarity.LEGENDARY,
    name: "VIP Crown Badge",
    description: "A premium badge showing VIP status.",
    icon: "badge_vip_crown_01",
    price: { currency: "GEMS", amount: 25 },
    vipOnly: true,
    unlockType: "VIP",
    limited: true,
  },
  {
    id: "badge_tournament_king",
    category: CosmeticCategory.BADGE,
    rarity: CosmeticRarity.LEGENDARY,
    name: "Tournament King Badge",
    description: "A legendary badge for tournament prestige.",
    icon: "badge_tournament_king_01",
    price: { currency: "GEMS", amount: 40 },
    unlockType: "EVENT",
    limited: true,
  },
  {
    id: "arena_banner_stadium_lights",
    category: CosmeticCategory.ARENA_BANNER,
    rarity: CosmeticRarity.RARE,
    name: "Stadium Lights Banner",
    description: "A bright arena banner for match intros.",
    icon: "arena_banner_stadium_lights_01",
    price: { currency: "COINS", amount: 500 },
  },
  {
    id: "arena_banner_galaxy_final",
    category: CosmeticCategory.ARENA_BANNER,
    rarity: CosmeticRarity.EPIC,
    name: "Galaxy Final Banner",
    description: "A cosmic arena banner for dramatic matchups.",
    icon: "arena_banner_galaxy_final_01",
    price: { currency: "GEMS", amount: 15 },
  },
  {
    id: "arena_banner_vip_gold",
    category: CosmeticCategory.ARENA_BANNER,
    rarity: CosmeticRarity.LEGENDARY,
    name: "VIP Gold Arena Banner",
    description: "A premium gold VIP banner for arena entrances.",
    icon: "arena_banner_vip_gold_01",
    price: { currency: "GEMS", amount: 45 },
    vipOnly: true,
    unlockType: "VIP",
    limited: true,
  },
  {
    id: "answer_trail_blue_comet",
    category: CosmeticCategory.ANSWER_TRAIL,
    rarity: CosmeticRarity.RARE,
    name: "Blue Comet Answer Trail",
    description: "A crisp comet trail for selected answers.",
    icon: "answer_trail_blue_comet_01",
    price: { currency: "COINS", amount: 400 },
  },
  {
    id: "answer_trail_green_check",
    category: CosmeticCategory.ANSWER_TRAIL,
    rarity: CosmeticRarity.COMMON,
    name: "Green Check Trail",
    description: "A clean success trail for answer taps.",
    icon: "answer_trail_green_check_01",
    price: { currency: "COINS", amount: 150 },
  },
  {
    id: "answer_trail_neon_lightning",
    category: CosmeticCategory.ANSWER_TRAIL,
    rarity: CosmeticRarity.EPIC,
    name: "Neon Lightning Trail",
    description: "A fast premium trail for confident answers.",
    icon: "answer_trail_neon_lightning_01",
    price: { currency: "GEMS", amount: 12 },
  },
  {
    id: "answer_trail_vip_crown",
    category: CosmeticCategory.ANSWER_TRAIL,
    rarity: CosmeticRarity.LEGENDARY,
    name: "VIP Crown Trail",
    description: "A VIP-only crown sparkle trail.",
    icon: "answer_trail_vip_crown_01",
    price: { currency: "GEMS", amount: 35 },
    vipOnly: true,
    unlockType: "VIP",
    limited: true,
  },
  {
    id: "streak_aura_blue_flame",
    category: CosmeticCategory.STREAK_AURA,
    rarity: CosmeticRarity.RARE,
    name: "Blue Flame Streak Aura",
    description: "A cool aura for strong streaks.",
    icon: "streak_aura_blue_flame_01",
    price: { currency: "COINS", amount: 500 },
  },
  {
    id: "streak_aura_neon_pulse",
    category: CosmeticCategory.STREAK_AURA,
    rarity: CosmeticRarity.EPIC,
    name: "Neon Pulse Streak Aura",
    description: "A premium pulsing aura for hot streaks.",
    icon: "streak_aura_neon_pulse_01",
    price: { currency: "GEMS", amount: 15 },
  },
  {
    id: "streak_aura_royal_vip",
    category: CosmeticCategory.STREAK_AURA,
    rarity: CosmeticRarity.LEGENDARY,
    name: "Royal VIP Streak Aura",
    description: "A VIP royal aura for elite streaks.",
    icon: "streak_aura_royal_vip_01",
    price: { currency: "GEMS", amount: 45 },
    vipOnly: true,
    unlockType: "VIP",
    limited: true,
  },
  {
    id: "streak_aura_legend_sun",
    category: CosmeticCategory.STREAK_AURA,
    rarity: CosmeticRarity.LEGENDARY,
    name: "Legend Sun Streak Aura",
    description: "A legendary golden aura for prestige collectors.",
    icon: "streak_aura_legend_sun_01",
    price: { currency: "GEMS", amount: 40 },
    unlockType: "SEASON",
    limited: true,
  },
];


